### ISSUE TITLE
Can task IDs now be integers rather than strings ?

### ISSUE THREAD

**Issue by martinval** [richardtallent/vue-simple-calendar#112] opened 2018-12-30 00:20 UTC
Hi Richard,
I'm using an adapted version of your 4.1.0 release and came across a build/deploy issue when using integer IDs for my tasks coming from the backend. Locally, all looks good, but once my app is deployed, the calendar reads the tasks as null. I've seen this mentioned as an issue in #104 and especially #65. Has this issue been resolved in 4.2.0 and IDs can now be integers ?
If yes, can you pls point me to the relevant function in CalendarView.
Thx

**Comment by richardtallent** [comment] 2018-12-30 05:16
The problem in #104 wasn't integer IDs, it was related to events that had no ID at all (the old code attempted to set a surrogate ID for them, but that had some significant issues, so now the `id` property is required for events).

The bug in #65 was not due to integer IDs *per se*, it was because the calendar's "day" components were using integer ids, and *if* you also used the same integers for event IDs, they would collide and lead to strange updates (since both the week's "days" and the week's "events" are drawn during the same `v-for` loop). That was fixed in 3.0.2 by changing the "day" component keys to something far less likely to collide with an event's `id`.

Not sure what you mean by "the calendar reads the tasks as null." Are you looking in Vue Dev Tools in Chrome and seeing a null somewhere unexpected in the state?

I'm not aware of any issue with events having integer IDs. The only other time the event's ID is used is tracking which event is being hovered over, and that code isn't dependent on the data type. If you can point to a reproducible example, please re-open and I'd be happy to take a look.

**Closed by richardtallent** 2018-12-30 05:16 UTC

**Comment by martinval** [comment] 2018-12-30 19:10
Thanks for clarifying. I've tested with a standard 4.2.0 version and all works fine. Must be some other issue in my project...
