### ISSUE TITLE
Weekperiod events not displaying correct

### ISSUE THREAD

**Issue by Shaegi** [richardtallent/vue-simple-calendar#89] opened 2018-08-11 15:24 UTC
Hey, 
first of all very cool component. 
For our application its important that every day of an event is in its own day with its own event tag. I did a small hack to accomplish that by just iterating throught the time span and adding an event for each day.
So far so good but somehow if I switch to week period there still a timespan of events. (Screenshot 1) Also if I click it it will show another date in my case 12.08.2018. 
This goes away if I go to next period and back again (screenshot 2). 

Any solution on this?
Ill add some screenshots. 

![image](https://user-images.githubusercontent.com/33374188/43993270-fd869362-9d8a-11e8-9d99-4fbf21c6d1fe.png)
![image](https://user-images.githubusercontent.com/33374188/43993280-12ae69b8-9d8b-11e8-9535-2b6730cb3534.png)
![image](https://user-images.githubusercontent.com/33374188/43993285-24f60946-9d8b-11e8-93dd-72bd1e050d38.png)

**Comment by richardtallent** [comment] 2018-08-13 02:29
I think you're on the right track by creating multiple instances of each event, one for each day. This is similar to the solution I just proposed for someone else who had a somewhat similar problem (handling repeating events).

There's nothing in the code that would create a multi-day spanned event out of individual day-long events, so without seeing your code, I can't really tell what's happening. My first guess is that your code that splits the events is not splitting them in the first screen shot.

It's also probably not related, but be sure to assign a separate `id` property to each *copy* of each event.

Please feel free to re-open this if you can't get it working and if you can put a reproducible version of your code online so we can see the issue live.

**Comment by Shaegi** [comment] 2018-08-13 05:18
Thanks for your answer. 
I did setup a code sandbox to have a reproduce online. https://codesandbox.io/s/rlv11ow1o4
As you can see in monthly view there is no problem only in week with the same event array passed.
I'd appreciate some help.

**Comment by richardtallent** [comment] 2018-08-21 03:49
I've been on vacation, so I haven't had a chance yet to look at this. Re-opening to remind me to do so.

**Comment by richardtallent** [comment] 2018-08-26 02:59
Hi, I was finally able to look at your issue, and it's actually a duplicate of #80 -- your `showDate` value has a time component, which creates a problem for week views.

This has been fixed in 4.0.2, just released on npm. I've updated and tested your sandbox:

https://codesandbox.io/s/88pm7qlq3l

**Closed by richardtallent** 2018-08-26 02:59 UTC
Labels: bug, duplicate

**Comment by Shaegi** [comment] 2018-08-26 10:15
Thanks very much!
